r"""
hvigor构建工具封装

重要发现 (2026-01-21):
- 不应使用项目目录下的hvigorw.bat/hvigorw脚本
- 应该使用DevEco Studio自带的hvigorw.js
- 路径: C:\Program Files\Huawei\DevEco Studio\tools\hvigor\bin\hvigorw.js
- 需要配合DevEco Studio自带的Node.js使用
"""
import subprocess
import os
import platform
import sys
from pathlib import Path
from typing import Dict, Any, Optional, List
from loguru import logger

# 添加父目录到路径以便导入config
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import Config


class HvigorWrapper:
    """hvigor构建系统封装类"""

    def __init__(self, project_path: str, deveco_path: Optional[str] = None):
        """
        初始化hvigor包装器

        Args:
            project_path: HarmonyOS项目路径
            deveco_path: DevEco Studio安装路径（可选，会自动检测）
        """
        self.project_path = Path(project_path)
        if not self.project_path.exists():
            raise ValueError(f"项目路径不存在: {project_path}")

        # 查找DevEco Studio路径
        self.deveco_path = self._find_deveco_studio(deveco_path)
        if not self.deveco_path:
            raise ValueError("未找到DevEco Studio安装路径")

        # 设置工具路径
        self.node_exe = self.deveco_path / "tools" / "node" / ("node.exe" if platform.system() == "Windows" else "node")
        self.hvigorw_js = self.deveco_path / "tools" / "hvigor" / "bin" / "hvigorw.js"

        # 验证工具存在
        if not self.node_exe.exists():
            raise ValueError(f"未找到Node.js: {self.node_exe}")
        if not self.hvigorw_js.exists():
            raise ValueError(f"未找到hvigorw.js: {self.hvigorw_js}")

        # 不修改local.properties，让DevEco Studio使用默认配置

        logger.info(f"初始化HvigorWrapper")
        logger.info(f"  项目路径: {project_path}")
        logger.info(f"  DevEco路径: {self.deveco_path}")
        logger.info(f"  Node.js: {self.node_exe}")
        logger.info(f"  hvigorw.js: {self.hvigorw_js}")

    def _find_deveco_studio(self, custom_path: Optional[str] = None) -> Optional[Path]:
        """查找DevEco Studio安装路径"""
        if custom_path:
            path = Path(custom_path)
            if path.exists():
                return path

        # Windows常见路径
        if platform.system() == "Windows":
            possible_paths = [
                Path("C:/Program Files/Huawei/DevEco Studio"),
                Path("C:/Program Files (x86)/Huawei/DevEco Studio"),
                Path(os.path.expanduser("~/AppData/Local/Huawei/DevEco Studio")),
            ]
        # macOS路径
        elif platform.system() == "Darwin":
            possible_paths = [
                Path("/Applications/DevEco Studio.app/Contents"),
                Path(os.path.expanduser("~/Applications/DevEco Studio.app/Contents")),
            ]
        # Linux路径
        else:
            possible_paths = [
                Path(os.path.expanduser("~/DevEco Studio")),
                Path("/opt/DevEco Studio"),
            ]

        for path in possible_paths:
            if path.exists():
                logger.info(f"找到DevEco Studio: {path}")
                return path

        return None

    def _ensure_local_properties(self):
        """确保local.properties配置正确"""
        local_props = self.project_path / "local.properties"
        # SDK路径应该指向default目录，hvigor会在子目录中查找SDK组件
        sdk_dir = self.deveco_path / "sdk" / "default"
        nodejs_dir = self.deveco_path / "tools" / "node"

        # 读取现有配置
        existing_config = {}
        if local_props.exists():
            with open(local_props, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        existing_config[key.strip()] = value.strip()

        # 更新配置
        needs_update = False
        if existing_config.get('sdk.dir') != str(sdk_dir).replace('\\', '\\\\'):
            needs_update = True
        if existing_config.get('nodejs.dir') != str(nodejs_dir).replace('\\', '\\\\'):
            needs_update = True

        if needs_update:
            logger.info(f"更新local.properties配置")
            with open(local_props, 'w', encoding='utf-8') as f:
                f.write("# This file is automatically generated by HarmonyOS MCP Server\n")
                f.write("# Do not modify this file manually\n\n")
                # 使用正斜杠路径，这是跨平台的标准格式
                sdk_path = str(sdk_dir).replace('\\', '/')
                nodejs_path = str(nodejs_dir).replace('\\', '/')
                f.write(f"sdk.dir={sdk_path}\n")
                f.write(f"nodejs.dir={nodejs_path}\n")
    
    def _execute_command(self, args: List[str], timeout: int = None) -> Dict[str, Any]:
        """
        执行hvigor命令

        Args:
            args: 命令参数列表（不包含node和hvigorw.js）
            timeout: 超时时间(秒)

        Returns:
            包含returncode, stdout, stderr的字典
        """
        # 构建完整命令: node hvigorw.js [args]
        cmd = [str(self.node_exe), str(self.hvigorw_js)] + args
        timeout = timeout or Config.BUILD_TIMEOUT

        logger.debug(f"执行构建命令: {' '.join(cmd)}")

        # 不设置任何SDK相关的环境变量，让DevEco Studio使用默认配置
        env = os.environ.copy()

        try:
            # 使用 DEVNULL 丢弃输出，完全避免管道和文件描述符问题
            # 使用 close_fds=True 确保子进程不继承任何文件描述符
            result = subprocess.run(
                cmd,
                cwd=str(self.project_path),
                stdout=subprocess.DEVNULL,  # 丢弃输出
                stderr=subprocess.DEVNULL,  # 丢弃错误输出
                stdin=subprocess.DEVNULL,   # 不接受输入
                timeout=timeout,
                env=env,
                close_fds=True  # 关闭所有文件描述符
            )

            return {
                'returncode': result.returncode,
                'stdout': '',  # 不返回输出
                'stderr': '',
                'success': result.returncode == 0
            }
        except subprocess.TimeoutExpired:
            # 超时了，记录错误
            logger.error(f"构建命令执行超时({timeout}秒)")
            return {
                'returncode': -1,
                'stdout': '',
                'stderr': f'构建超时({timeout}秒)',
                'success': False
            }
        except Exception as e:
            logger.error(f"构建命令执行失败: {e}")
            return {
                'returncode': -1,
                'stdout': '',
                'stderr': str(e),
                'success': False
            }

    def _kill_process_tree(self, pid: int):
        """
        终止进程及其所有子进程

        Args:
            pid: 进程ID
        """
        import platform
        try:
            if platform.system() == 'Windows':
                # 在 Windows 上使用 taskkill 终止进程树
                subprocess.run(
                    ['taskkill', '/F', '/T', '/PID', str(pid)],
                    capture_output=True,
                    timeout=5
                )
            else:
                # 在 Unix 系统上使用 kill
                import signal
                os.killpg(os.getpgid(pid), signal.SIGTERM)
        except Exception as e:
            logger.error(f"终止进程树失败: {e}")
    
    def clean(self, product: str = "default") -> Dict[str, Any]:
        """
        清理构建产物

        Args:
            product: 产品名称（品类）

        Returns:
            构建结果
        """
        logger.info("清理构建产物")
        args = [
            '--sync',
            '-p', f'product={product}',
            '--analyze=normal',
            '--parallel',
            '--incremental'
            # 移除 --no-daemon 参数，因为我们使用 DEVNULL 避免了所有 daemon 相关问题
        ]
        result = self._execute_command(args)

        if result['success']:
            logger.info("清理成功")
        else:
            logger.error(f"清理失败: {result['stderr']}")

        return result

    def build_har(self, module_name: str, product: str = "default") -> Dict[str, Any]:
        """
        构建HAR包

        Args:
            module_name: 模块名称
            product: 产品名称（品类）

        Returns:
            构建结果,包含HAR包路径
        """
        logger.info(f"构建HAR包 (模块: {module_name}, 产品: {product})")

        args = [
            '--mode', 'module',
            '-p', f'product={product}',
            '-p', f'module={module_name}',
            'assembleHar',
            '--analyze=normal',
            '--parallel',
            '--incremental'
            # 移除 --daemon 参数，避免 subprocess.run() 阻塞等待 daemon 进程
        ]

        result = self._execute_command(args)

        if result['success']:
            # 查找生成的HAR包
            har_path = self._find_build_output('har', module_name)
            result['har_path'] = str(har_path) if har_path else None
            logger.info(f"HAR包构建成功: {result['har_path']}")
        else:
            logger.error(f"HAR包构建失败: {result['stderr']}")

        return result

    def build_hap(self, build_mode: str = "debug", product: str = "default") -> Dict[str, Any]:
        """
        构建HAP包

        Args:
            build_mode: 构建模式 (debug/release)
            product: 产品名称（品类）

        Returns:
            构建结果,包含HAP包路径
        """
        logger.info(f"构建HAP包 (模式: {build_mode}, 产品: {product})")

        args = [
            '--mode', 'module',
            '-p', f'product={product}',
            'assembleHap',
            '--analyze=normal',
            '--parallel',
            '--incremental'
            # 移除 --daemon 参数，避免 subprocess.run() 阻塞等待 daemon 进程
        ]

        result = self._execute_command(args)

        if result['success']:
            # 查找生成的HAP包
            hap_path = self._find_build_output('hap', build_mode)
            result['hap_path'] = str(hap_path) if hap_path else None
            logger.info(f"HAP包构建成功: {result['hap_path']}")
        else:
            logger.error(f"HAP包构建失败: {result['stderr']}")
        
        return result

    def build_app(self, build_mode: str = "debug", product: str = "default") -> Dict[str, Any]:
        """
        构建APP包（最终上架包）

        Args:
            build_mode: 构建模式 (debug/release)
            product: 产品名称（品类）

        Returns:
            构建结果,包含APP包路径
        """
        logger.info(f"构建APP包 (模式: {build_mode}, 产品: {product})")

        args = [
            '-p', f'product={product}',
            'assembleApp',
            '--analyze=normal',
            '--parallel',
            '--incremental'
            # 移除 --daemon 参数，避免 subprocess.run() 阻塞等待 daemon 进程
        ]

        result = self._execute_command(args)

        if result['success']:
            # 查找生成的APP包
            app_path = self._find_build_output('app', build_mode)
            result['app_path'] = str(app_path) if app_path else None
            logger.info(f"APP包构建成功: {result['app_path']}")
        else:
            logger.error(f"APP包构建失败: {result['stderr']}")

        return result

    def _find_build_output(self, output_type: str, search_key: str = "") -> Optional[Path]:
        """
        查找构建输出文件

        Args:
            output_type: 输出类型 (har/hap/app)
            search_key: 搜索关键字（模块名或构建模式）

        Returns:
            输出文件路径
        """
        # 常见的输出路径
        output_dirs = [
            self.project_path / 'build',
            self.project_path / 'entry' / 'build',
        ]

        # 如果是HAR，还要搜索模块目录
        if output_type == 'har' and search_key:
            output_dirs.append(self.project_path / search_key / 'build')

        for output_dir in output_dirs:
            if not output_dir.exists():
                continue

            # 查找对应类型的文件
            extension = f'.{output_type}'
            for file in output_dir.rglob(f'*{extension}'):
                return file

        return None

    def get_build_info(self) -> Dict[str, Any]:
        """
        获取构建信息

        Returns:
            构建信息字典
        """
        info = {
            'project_path': str(self.project_path),
            'deveco_path': str(self.deveco_path),
            'node_exe': str(self.node_exe),
            'hvigorw_js': str(self.hvigorw_js),
            'has_build_profile': (self.project_path / 'build-profile.json5').exists(),
            'has_local_properties': (self.project_path / 'local.properties').exists(),
        }

        return info

